name: Deploy Caddy

on:
  push:
    branches:
      - main  # Triggers when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key

      - name: Deploy to Droplet
        run: |
          ssh -i private_key -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'

            echo "🔹 Navigating to project directory..."
            cd /home/apps/caddy || { echo "❌ Folder not found!"; exit 1; }
            git pull origin main
            docker-compose down
            docker-compose up -d
          EOF
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
