name: Deploy Caddy

on:
  push:
    branches:
      - main  # Runs this when you push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /home/${{ secrets.DO_USER }}/caddy
            git pull origin main
            docker compose down
            docker compose up -d --build
